### ISSUE TITLE
Passkey Support 

### ISSUE THREAD

**Issue by freddyyeddy** [trustcrypto/OnlyKey-Firmware#174]
Now it seems google, and other major companies are moving towards the fido passkey model (https://fidoalliance.org/passkeys/). Would we be able to get this supported with the onlykeys (DUO and or OG).

**Comment by onlykey** [comment]
"Passkey technology is the cybersecurity industry’s attempt to unify, streamline, modernize and rebrand existing authentication lexicon, even if the underlying technology is essentially identical to FIDO2/WebAuthn, which has existed since 2018."

OnlyKey supports passkeys, this is essentially the same as passwordless FIDO2

**Comment by ElonGaties** [comment]
could issues like these be marked as resolved? as the question/issue seems to have been answered, i dont see much reason in leaving the issue open
